# Generated by Django 2.1.2 on 2018-12-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('credit', models.IntegerField(default=2)),
                ('semester', models.CharField(max_length=6)),
                ('major', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.UserInfo')),
            ],
        ),
    ]
