# Generated by Django 2.1.2 on 2018-12-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_loginuser_user_info_usertodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.LoginUser'),
        ),
    ]
