# Generated by Django 2.1.2 on 2018-12-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20181211_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='mail',
        ),
    ]
