# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.TextField()),
                ('first', models.TextField()),
                ('special', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.TextField()),
                ('first', models.TextField()),
                ('special', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.TextField()),
                ('first', models.TextField()),
                ('special', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libname', models.CharField(max_length=20)),
                ('floor', models.DecimalField(decimal_places=0, max_digits=5)),
                ('room', models.CharField(max_length=20)),
                ('whole', models.DecimalField(decimal_places=0, max_digits=5)),
                ('used', models.DecimalField(decimal_places=0, max_digits=5)),
                ('rest', models.DecimalField(decimal_places=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
