# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-07 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooda',
            name='week',
            field=models.CharField(default='\uc6d4', max_length=5),
            preserve_default=False,
        ),
    ]
