# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovigation', '0002_fooda_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodb',
            name='week',
            field=models.CharField(default='\uc6d4', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodc',
            name='week',
            field=models.CharField(default='\uc6d4', max_length=5),
            preserve_default=False,
        ),
    ]
