# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovigation', '0003_auto_20181107_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=50)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('hits', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
